### ISSUE TITLE
Not loading the icons list

### ISSUE THREAD

**Issue by mehmood-v** [bgrand-ch/grapesjs-icons#5]
I configured it with grapes js according to the documentation but it's not loading the icons.

![React-App](https://github.com/bgrand-ch/grapesjs-icons/assets/95611144/52b51f96-e561-4c8a-979c-e17ea0ef1923)

**Comment by bgrand-ch** [comment]
Hello, could you show me the configuration of the `grapesjs-icons` plugin please?

You should use the abbreviation of the icon library. The full name will be implemented soon.

Example with "Remix icons" (Remix = "ri" in URL):
https://icon-sets.iconify.design/ri/

![Screenshot 2023-10-23 at 12 59 38](https://github.com/bgrand-ch/grapesjs-icons/assets/17108974/f724c197-ade1-418c-a9be-fcaf83157775)

**Comment by bgrand-ch** [comment]
Discussion https://github.com/bgrand-ch/grapesjs-icons/discussions/6
